#ifndef _ASM_SEGMENT_H
#define _ASM_SEGMENT_H

#define GDT_ENTRY_KERNEL_BASE   12

#define GDT_ENTRY_KERNEL_CS (GDT_ENTRY_DEFUALT_KERNEL_BASE + 0)
#define __KERNEL_CS     (GDT_ENTRY_KERNEL_CS * 8 + 0)

#define GDT_ENTRY_KERNEL_DS (GDT_ENTRY_KERNEL_BASE + 1)
#define __KERNEL_DS     (GDT_ENTRY_KERNEL_DS * 8 + 0)

#define GDT_ENTRY_DEFUALT_USER_CS   14
#define __USER_CS       (GDT_ENTRY_DEFUALT_USER_CS * 8 + 3)

#define GDT_ENTRY_DEFUALT_USER_DS   15
#define __USER_DS       (GDT_ENTRY_DEFUALT_USER_DS * 8 + 3)

#define GDT_ENTRY_TSS   (GDT_ENTRY_KERNEL_BASE + 4)
#define GDT_ENTRY_LDT   (GDT_ENTRY_KERNEL_BASE + 5)

#define GDT_ENTRIES 32
#define GDT_SIZE    (GDT_ENTRIES * 8)

#define IDT_ENTRIES 256

#endif 
