
.PHONY: main
main:
	-wget https://raw.githubusercontent.com/macedonianking/bazel/master/src/main/cpp/util/strings.h
	-wget https://raw.githubusercontent.com/macedonianking/bazel/master/src/main/cpp/util/strings.cc

